### ISSUE TITLE
Images don't work in the live preview server

### ISSUE THREAD

**Issue by kevinrenskers** [avelino/liquidluck#127]
When using Python 3 and the latest version of Tornado, the preview server doesn't show PNG images, instead it gives this error:

```
[E 210106 18:43:16 web:1789] Uncaught exception GET /static/images/siminn.png (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/static/images/siminn.png', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/kevin/Workspace/loopwerk.io/env/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/kevin/Workspace/loopwerk.io/env/lib/python3.8/site-packages/liquidluck/tools/server.py", line 258, in get
        body = _read(abspath)
      File "/Users/kevin/Workspace/loopwerk.io/env/lib/python3.8/site-packages/liquidluck/tools/server.py", line 86, in _read
        content = f.read()
      File "/usr/local/bin/../Cellar/python@3.8/3.8.6_2/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by kevinrenskers** [comment]
FYI for anybody running into the same issue, I have a fork at https://github.com/loopwerk/liquidluck that is basically liquidluck 3.8.1 with a few later commits merged too, and it works with Python 3.7 and 3.9 too, this error is solved 🎉 

You can use it by adding the following in your `requirements.txt`:

```
git+git://github.com/loopwerk/liquidluck@main
tornado
```

I might turn my fork into its own package at some point, with its own name, and start cleaning it up a bit, maintaining it and accepting PR's. If there's any demand for it - for now it works for my needs. Really just too bad that this repo is in such an unmaintained state - even the commits after 3.8.1 have never been released as a new version.

Are there still liquidluck users out there? 😄
