### ISSUE TITLE
exception when using Python 3 version

### ISSUE THREAD

**Issue by tshepang** [avelino/liquidluck#95]
Following is the output of running `liquidluck server` and visiting http://localhost:8000:

```
[I 130419 17:49:48 generator:88] Load Settings Finished
[I 130419 17:49:53 generator:135] Load Posts Finished
[I 130419 17:49:54 base:47] PostWriter Finished
[I 130419 17:49:54 base:47] PageWriter Finished
[I 130419 17:49:55 base:47] ArchiveWriter Finished
[I 130419 17:49:55 base:47] ArchiveFeedWriter Finished
[I 130419 17:49:55 base:47] FileWriter Finished
[I 130419 17:49:55 base:47] StaticWriter Finished
[I 130419 17:49:55 base:47] YearWriter Finished
[I 130419 17:49:55 base:47] CategoryWriter Finished
[I 130419 17:49:56 base:47] CategoryFeedWriter Finished
[I 130419 17:49:56 base:47] TagWriter Finished
[I 130419 17:49:57 base:47] TagCloudWriter Finished
[I 130419 17:49:57 server:307] Theme directory: /home/tshepang/projects/liquidluck/build/lib/liquidluck/_themes/default
[I 130419 17:49:57 server:316] Start server at 127.0.0.1:8000
[I 130419 17:50:00 server:167] Browser Connected: http://localhost:8000/
[I 130419 17:50:00 server:171] Start watching changes
[I 130419 17:50:09 web:1514] 304 GET / (127.0.0.1) 4.42ms
[I 130419 17:50:09 web:1514] 304 GET /static/style.css?v=2c4d4 (127.0.0.1) 1.37ms
[I 130419 17:50:09 web:1514] 304 GET /static/pygments.css?v=c6adc (127.0.0.1) 1.23ms
[I 130419 17:50:09 web:1514] 304 GET /livereload.js (127.0.0.1) 1.16ms
[I 130419 17:50:09 web:1514] 304 GET /static/mobile.js?v=3b6df (127.0.0.1) 0.64ms
[E 130419 17:50:09 web:1121] Uncaught exception GET /static/end.png (127.0.0.1)
    HTTPRequest(protocol='http', host='localhost:8000', method='GET', uri='/static/end.png', version='HTTP/1.1', remote_ip='127.0.0.1', body='', headers={'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': 'localhost:8000', 'Referer': 'http://localhost:8000/', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.63 Safari/537.31'})
    Traceback (most recent call last):
      File "/home/tshepang/venv/33/lib/python3.3/site-packages/tornado-3.0.1-py3.3.egg/tornado/web.py", line 1077, in _execute
        *self.path_args, **self.path_kwargs)
      File "/home/tshepang/projects/liquidluck/build/lib/liquidluck/tools/server.py", line 258, in get
        body = _read(abspath)
      File "/home/tshepang/projects/liquidluck/build/lib/liquidluck/tools/server.py", line 86, in _read
        content = f.read()
      File "/home/tshepang/opt/py33/lib/python3.3/codecs.py", line 300, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
[E 130419 17:50:09 web:1514] 500 GET /static/end.png (127.0.0.1) 3.68ms
[I 130419 17:50:09 server:167] Browser Connected: http://localhost:8000/
[W 130419 17:50:10 web:1514] 404 GET /favicon.ico (127.0.0.1) 0.83ms
```

I don't know why this doesn't fail on Python 2. Maybe because it's less strict?

My workaround is at https://github.com/tshepang/liquidluck/blob/c16008fbd6123d0a126cb4bae7387734ac2e37e2/liquidluck/tools/server.py#L86.

**Comment by kevinrenskers** [comment]
I'm running into the same issue where image files are not served, instead giving the error 500. What was that workaround that you mentioned?

**Comment by tshepang** [comment]
sorry I removed the fork... didn't think anyone would find it useful since it was so old

**Comment by kevinrenskers** [comment]
For people running into the same issue, check out #127 for a fork that works, or #128 for just the changes needed to get it to work.
